### ISSUE TITLE
Proguard rules not complete

### ISSUE THREAD

**Issue by sschendel** [optimizely/android-sdk#113]
Running version 1.3.0 with the proguard rules from documentation:

```
# Optimizely
-keep class com.optimizely.ab.** { *; }

# Gson
-keepnames class com.google.gson.Gson

# Safely ignore warnings about other libraries since we are using Gson
-dontwarn com.fasterxml.jackson.**
-dontwarn org.json.**

# Annotations
-dontwarn javax.annotation.**

# Findbugs
-dontwarn edu.umd.cs.findbugs.annotations.SuppressFBWarnings

# slf4j
-dontwarn org.slf4j.**
```

App crashes with missing class exception for Optimizely dependent class:
`com.noveogroup.android.log.Utils`

Perhaps proguard rules should be updated to address this?

I added rule to work around:
```
-keep class com.noveogroup.android.log.** { *; }
```

**Comment by manuel-sejourne** [comment]
Thank you for your post

**Comment by elliotykim** [comment]
Hi @sschendel, thanks for posting the issue and also the solution. I've updated the documentation which should be published next week.

Also I've added the suggested Proguard rules to our test-app:
https://github.com/optimizely/android-sdk/commit/4e7b715ba3619bd8e9edf1655704026c88b1372a
