### ISSUE TITLE
ExceptionInInitializerError not catched

### ISSUE THREAD

**Issue by julienaba** [optimizely/android-sdk#117]
Hi there,

I'm getting an error in production while initializing Optimizely :

> Fatal Exception: java.lang.ExceptionInInitializerError
>        at org.apache.harmony.security.x509.Validity.(Validity.java)
>        at org.apache.harmony.security.x509.TBSCertificate.(TBSCertificate.java)
>        at org.apache.harmony.security.x509.Certificate.(Certificate.java)
>        at org.apache.harmony.security.pkcs7.SignedData.(SignedData.java)
>        at org.apache.harmony.security.pkcs7.ContentInfo$1.getDecodedObject(ContentInfo.java:146)
>        at org.apache.harmony.security.asn1.ASN1Sequence.decode(ASN1Sequence.java:45)
>        at org.apache.harmony.security.utils.JarUtils.verifySignature(JarUtils.java:72)
>        at java.util.jar.JarVerifier.verifyCertificate(JarVerifier.java:294)
>        at java.util.jar.JarVerifier.readCertificates(JarVerifier.java:268)
>        at java.util.jar.JarFile.getInputStream(JarFile.java:380)
>        at libcore.net.url.JarURLConnectionImpl.getInputStream(JarURLConnectionImpl.java:222)
>        at java.net.URL.openStream(URL.java:470)
>        at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:444)
>        at com.noveogroup.android.log.LoggerManager.loadProperties(LoggerManager.java:77)
>        at com.noveogroup.android.log.LoggerManager.loadConfiguration(LoggerManager.java:123)
>        at com.noveogroup.android.log.LoggerManager.(LoggerManager.java)
>        at org.slf4j.impl.AndroidLoggerFactory.getLogger(AndroidLoggerFactory.java:41)
>        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:329)
>        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:349)
>        at com.optimizely.ab.android.sdk.OptimizelyManager$Builder.build(OptimizelyManager.java:627)
>        [...]
>  
> Caused by java.lang.ArithmeticException: BigInteger division by zero
>        at java.math.NativeBN.BN_new(NativeBN.java)
>        at java.math.BigInt.makeValid(BigInt.java:51)
>        at java.math.BigInt.putULongInt(BigInt.java:85)
>        at java.math.BigInteger.(BigInteger.java)
>        at java.math.BigInteger.valueOf(BigInteger.java:373)
>        at org.apache.harmony.security.asn1.ASN1Choice.addIdentifier(ASN1Choice.java:282)
>        at org.apache.harmony.security.asn1.ASN1Choice.(ASN1Choice.java)
>        at org.apache.harmony.security.x509.Time$1.(Time.java)
>        at org.apache.harmony.security.x509.Time.(Time.java)
>        at org.apache.harmony.security.x509.Validity.(Validity.java)
>        at org.apache.harmony.security.x509.TBSCertificate.(TBSCertificate.java)
>        at org.apache.harmony.security.x509.Certificate.(Certificate.java)
>        at org.apache.harmony.security.pkcs7.SignedData.(SignedData.java)
>        at org.apache.harmony.security.pkcs7.ContentInfo$1.getDecodedObject(ContentInfo.java:146)
>        at org.apache.harmony.security.asn1.ASN1Sequence.decode(ASN1Sequence.java:45)
>        at org.apache.harmony.security.utils.JarUtils.verifySignature(JarUtils.java:72)
>        at java.util.jar.JarVerifier.verifyCertificate(JarVerifier.java:294)
>        at java.util.jar.JarVerifier.readCertificates(JarVerifier.java:268)
>        at java.util.jar.JarFile.getInputStream(JarFile.java:380)
>        at libcore.net.url.JarURLConnectionImpl.getInputStream(JarURLConnectionImpl.java:222)
>        at java.net.URL.openStream(URL.java:470)
>        at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:444)
>        at com.noveogroup.android.log.LoggerManager.loadProperties(LoggerManager.java:77)
>        at com.noveogroup.android.log.LoggerManager.loadConfiguration(LoggerManager.java:123)
>        at com.noveogroup.android.log.LoggerManager.(LoggerManager.java)
>        at org.slf4j.impl.AndroidLoggerFactory.getLogger(AndroidLoggerFactory.java:41)
>        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:329)
>        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:349)
>        at com.optimizely.ab.android.sdk.OptimizelyManager$Builder.build(OptimizelyManager.java:627)
>        [...]

This seems to be a problem while initializing the Logger in Optimizely build() line 627 :
```
            try {
                logger = LoggerFactory.getLogger(OptimizelyManager.class);
            } catch (Exception e) {
                logger = LoggerFactory.getLogger("Optly.androidSdk");
                logger.error("Unable to generate logger from class");
            }
```
This snippet is catching Exceptions but not Errors like "java.lang.ExceptionInInitializerError". 
A simple workaround is to add "catch(Error e){ [...] }" as well.

If you need any further infos, just tell me.

**Comment by elliotykim** [comment]
Hi @julienaba,

Thanks for reporting the problem and including so many details. We'll discuss internally how to proceed and get back to you if we need anything else.

**Comment by julienaba** [comment]
Ok thanks, keep me in touch 👍

**Comment by manuel-sejourne** [comment]
I am facing to this issue too.

**Comment by manuel-sejourne** [comment]
when the new SDK version will be available ?

**Comment by elliotykim** [comment]
Hi @manuel-sejourne,

@thomaszurkan-optimizely can answer your question about the new release.

I've been investigating the error and have a question. Do you have a file called `android-logger.properties` in your project? The error seems to occur when loading it.

**Comment by elliotykim** [comment]
@manuel-sejourne and @julienaba,

Here's the suggested change which will be included in the 1.4.0 release:
https://github.com/optimizely/android-sdk/pull/132

However, I suspect we'll still have issues instantiating `logger`.

So far I haven't been able to reproduce the error, so it's difficult to investigate further. Could you share with me what devices and Android versions you're seeing this problem with? If I can reliable reproduce the error, I can provide a better fix.

-Elliot

**Comment by thomaszurkan-optimizely** [comment]
@manuel-sejourne and @julienaba,
Are you still having this problem with android-sdk 1.4.0 or may I close this issue?  Thanks!

**Comment by thomaszurkan-optimizely** [comment]
I'm closing this issue with the release of 1.4.0.  Please feel free to reopen if you see this problem again.  Thank you.
