### ISSUE TITLE
DataFileLoader - OutOfMemory

### ISSUE THREAD

**Issue by manuel-sejourne** [optimizely/android-sdk#128]
Hi,

We are facing an issue in PRODUCTION with your SDK.

OS Version : Android 6.0

Here is the stacktrace :

DataFileLoader.java line 71

java.lang.OutOfMemoryError: Could not allocate JNI Env
--
  | 1 | at java.lang.Thread.nativeCreate(Thread.java)
  | 2 | at java.lang.Thread.start(Thread.java:1063)
  | 3 | at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)
  | 4 | at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1328)
  | 5 | at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:584)
  | 6 | at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:607)
! | 7 | at com.optimizely.ab.android.sdk.DataFileLoader.getDataFile(DataFileLoader.java:71)
  | 8 | at com.optimizely.ab.android.sdk.DataFileService.onStartCommand(DataFileService.java:73)
  | 9 | at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3202)
  | 10 | at android.app.ActivityThread.-wrap17(ActivityThread.java)
  | 11 | at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1600)
  | 12 | at android.os.Handler.dispatchMessage(Handler.java:111)
  | 13 | at android.os.Looper.loop(Looper.java:207)
  | 14 | at android.app.ActivityThread.main(ActivityThread.java:5763)
  | 15 | at java.lang.reflect.Method.invoke(Method.java)
  | 16 | at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
  | 17 | at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by elliotykim** [comment]
Hi @manuel-sejourne,

We really appreciate that you reported this issue. It should be resolved here: https://github.com/optimizely/android-sdk/pull/130

Thanks and please continue to let us know when you find problems.

-Elliot
