### ISSUE TITLE
IncompatibleClassChangeError - Couldn't find com.fasterxml.jackson.annotation.JsonIgnoreProperties.ignoreUnknown

### ISSUE THREAD

**Issue by manuel-sejourne** [optimizely/android-sdk#129]
Hello,

We encounter an issue using your SDK on API 17. Here is the stacktrace:

Reason	
Couldn't find com.fasterxml.jackson.annotation.JsonIgnoreProperties.ignoreUnknown

Crashed Thread
  | 0 | java.lang.IncompatibleClassChangeError: Couldn't find com.fasterxml.jackson.annotation.JsonIgnoreProperties.ignoreUnknown
-- | -- | --
  | 1 | at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:659)
  | 2 | at libcore.reflect.AnnotationAccess.annotationSetToAnnotations(AnnotationAccess.java:633)
  | 3 | at libcore.reflect.AnnotationAccess.getDeclaredAnnotations(AnnotationAccess.java:161)
  | 4 | at java.lang.Class.getDeclaredAnnotations(Class.java:891)
! | 5 | at aad.q(aad.java:954)
  | 6 | at so.o(so.java:409)
  | 7 | at so.<init>(so.java:158)
  | 8 | at so.a(so.java:203)
  | 9 | at sy.a(sy.java:190)
  | 10 | at sy.a(sy.java:111)
  | 11 | at sy.f(sy.java:16)
  | 12 | at com.fasterxml.jackson.databind.f.b(f.java:900)
  | 13 | at pk.f(pk.java:324)
  | 14 | at pk.e(pk.java:264)
  | 15 | at pk.d(pk.java:244)
  | 16 | at pk.a(pk.java:142)
  | 17 | at com.fasterxml.jackson.databind.g.b(g.java:476)
  | 18 | at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3899)
  | 19 | at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3794)
  | 20 | at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842)
  | 21 | at com.optimizely.ab.config.parser.JacksonConfigParser.parseProjectConfig(JacksonConfigParser.java:39)
  | 22 | at com.optimizely.ab.Optimizely.getProjectConfig(Optimizely.java:468)
  | 23 | at com.optimizely.ab.Optimizely.access$000(Optimizely.java:87)
  | 24 | at com.optimizely.ab.Optimizely$Builder.build(Optimizely.java:714)
  | 25 | at com.optimizely.ab.android.sdk.OptimizelyManager.buildOptimizely(OptimizelyManager.java:395)
  | 26 | at com.optimizely.ab.android.sdk.OptimizelyManager.access$400(OptimizelyManager.java:62)
  | 27 | at com.optimizely.ab.android.sdk.OptimizelyManager$1.onPostExecute(OptimizelyManager.java:364)
  | 28 | at com.optimizely.ab.android.sdk.OptimizelyManager$1.onPostExecute(OptimizelyManager.java:350)
  | 29 | at android.os.AsyncTask.finish(AsyncTask.java:632)
  | 30 | at android.os.AsyncTask.access$600(AsyncTask.java:177)
  | 31 | at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
  | 32 | at android.os.Handler.dispatchMessage(Handler.java:102)
  | 33 | at android.os.Looper.loop(Looper.java:145)
  | 34 | at android.app.ActivityThread.main(ActivityThread.java:5951)
  | 35 | at java.lang.reflect.Method.invoke(Method.java)
  | 36 | at java.lang.reflect.Method.invoke(Method.java:372)
  | 37 | at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
  | 38 | at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

**Comment by elliotykim** [comment]
Hi @manuel-sejourne,

So far we've only run into this issue with Samsung devices running Android 5 and older. If you're seeing it on other devices, please let us know.

This fix should be prevent the error from crashing the app:
https://github.com/optimizely/android-sdk/commit/57b2168a8b3aa9257150f3b19f2f97b18eacd39f

It'll be released in 1.4.0 which should be soon.

**Comment by manuel-sejourne** [comment]
Thanks for your feedback
