### ISSUE TITLE
ProGuard rules should be provided by the library

### ISSUE THREAD

**Issue by wkarl** [optimizely/android-sdk#135]
Having to add ProGuard rules on the application side is cumbersome and can break with library updates.

Please provide the rules via the library's build.gradle so they are automatically applied when the library is used in a proguarded app:

`android {
    defaultConfig {
        consumerProguardFiles 'proguard-rules.pro'
    }
}`

**Comment by thomaszurkan-optimizely** [comment]
thank you for the feedback.  1.4.0-beta-RC-2 will have this update and will be released today.

**Comment by wkarl** [comment]
Great, thank you! BTW I noticed there are no files on jcenter for 1.4.0-beta-RC1

**Comment by thomaszurkan-optimizely** [comment]
Thanks!  They are there now

**Comment by thomaszurkan-optimizely** [comment]
I'm closing this since now we have consumerProguardFiles (android-sdk 1.4.0).  If there are any problems with the implementation, please feel free to reopen this. thanks!
