### ISSUE TITLE
Android O boot receiver support 

### ISSUE THREAD

**Issue by debaj** [optimizely/android-sdk#137]
Library version: 1.3.1, 1.4.0-alpha
Steps to reproduce:
- Prepare a test app for API level 26
- For 1.4.0: add the DatafileRescheduler, EventRescheduler receivers to the test app manifest
- Install the app
- Reboot the device

Expected: The boot receivers start without problem.
Actual: The receivers crash

Log:
`java.lang.RuntimeException: Unable to start receiver com.optimizely.ab.android.event_handler.EventRescheduler: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=de.mobile.android.app.debug/com.optimizely.ab.android.event_handler.EventIntentService }: app is in background uid UidRecord{afa610a u0a140 TRNB idle procs:1 seq(0,0,0)}
   at android.app.ActivityThread.handleReceiver(ActivityThread.java:3259)
   at android.app.ActivityThread.-wrap17(Unknown Source:0)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
   at android.os.Handler.dispatchMessage(Handler.java:105)
   at android.os.Looper.loop(Looper.java:164)
   at android.app.ActivityThread.main(ActivityThread.java:6541)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)`

**Comment by thomaszurkan-optimizely** [comment]
Hi,
Are you on the latest beta version of Android O?  I tried to get it to fail on the simulator and could not.  I'm running on android-sdk-beta-rc2.  I'm just running the test_app.  I installed it as a signed release apk.  I'm using a Nexus 6 emulator with Android 8.0 (API 26).  I used the adb shell command as root to broadcast a BOOT_COMPLETED.  It didn't give me an exceptions.

**Comment by debaj** [comment]
Hi,

Right now we target API level 25, this issue was identified during our migration to API level 26. We would like to launch our Android O support as soon as possible after it goes live. So this is not a blocker issue for us at the moment but we wanted to notify you guys about the possible breaking change.

**Comment by thomaszurkan-optimizely** [comment]
Thanks!  Glad to hear it isn't a blocker.  We are going to release 1.4.0 and then tackle Android O in 1.4.1 (refactor to use JobScheduler).

**Comment by Daio-io** [comment]
You just need to change your IntentService to JobIntentService then call JobIntentService.enque. This will handle the compat between Android O and lower versions 😄

**Comment by thomaszurkan-optimizely** [comment]
Thanks!  I did see that.  We just need to do a little testing first.

**Comment by tmtrademarked** [comment]
Any ETA on supporting this? We're trying to target API 26 currently, and are running into the same problem. (We can lower our targeting for now, but would like to know when this is expected to be fixed)

**Comment by Daio-io** [comment]
We have taken the decision to turn off Optimizely for API 26. Hopefully you guys can support it soon

**Comment by thomaszurkan-optimizely** [comment]
Are you targeting API 26?

**Comment by Daio-io** [comment]
Yeah we are 🤖

**Comment by thomaszurkan-optimizely** [comment]
@Daio-io keep in mind that you don't need those intent filters.  You can leave them out of your manifest and you shouldn't have a problem.  Those services just restart background services on reboot, update, and for events wifi available.  The "wifi available" service can be registered via api in your app and not through the manifest,  this should also work for you.

**Comment by thomaszurkan-optimizely** [comment]
FYI:  Working on a solution now.  Should be out soon.

**Comment by thomaszurkan-optimizely** [comment]
We're just wrapping up testing on this.  What we have done is with API 26 and beyond we use JobScheduler for starting all jobs (foreground or background).  We are using the JobWorkItem along with JobWorkServie to queue work when not scheduling, and using a scheduled job service when scheduling a job (the job is persistent so it will automatically be restarted on a reinstall and reboot).  

The cool part is that we keep the alarm system and normal start intact for everything pre API 26.  So, we have a solution that works for all moving forward and is backward compatible.  I hope to have it out this week.

Developers can take advantage of this mechanism via the ServiceScheduler.schedule and ServiceScheduler.startService.  The only problem with the scheduler is that right now I'm only copying extras that are string or long type for scheduled intents.

Hope that makes sense.  Developer docs will be updated to explain this more fully.

**Comment by thomaszurkan-optimizely** [comment]
@Daio-io @mrmike We have released Android SDK 1.5.0-RC.  It has API 26 as its target.  Please give it a go and let me know if you have any issues.  I will be closing this issue soon.

**Comment by thomaszurkan-optimizely** [comment]
Support for Android O and above in SDK 1.5.0
