### ISSUE TITLE
Consider removing dependency on https://github.com/noveogroup/android-logger

### ISSUE THREAD

**Issue by benoitdion** [optimizely/android-sdk#140]
As a third party sdk you may not want to force slf4j and an implementation to your users. It also easily conflicts with other slf4j implementations (we use https://github.com/tomakehurst/wiremock in our tests and had to do some odd gradle magic to get everything working together). noveogroup/android-logger also hasn't been updated since 2015

**Comment by thomaszurkan-optimizely** [comment]
Thanks!  It doesn't look like we will get to this for 1.4.0 which will be releasing soon.  But, we are going to go over all our dependencies and upgrade as many as we can.  This one is at the top of list.  Thanks for taking the time to file a issue.  Look for this to be closed soon.  :)

**Comment by benoitdion** [comment]
great to hear! on the topic of dependency it'd also be great if you allowed to set a json deserializer instead of forcing either gson or jackson.

**Comment by thomaszurkan-optimizely** [comment]
good idea.  thanks.

**Comment by sayedhassan** [comment]
We are also facing this issue. Our release build fails with the following error. 

```
Warning:Exception while processing task java.io.IOException: Can't write  
    [.../app/build/intermediates/transforms/proguard/release/jars/3/1f/main.ja] 
    (Can't read [.../.gradle/caches/modules-2/files 
2.1/com.noveogroup.android/android-
logger/1.3.6/5cb3345e23efd3d3a195eb8c4ae5b627189f8159/android-logger-
1.3.6.jar(;;;;;;**.class)] (Duplicate zip entry [org/b/c/a.class == 
android-logger-1.3.6.jar:org/slf4j/impl/StaticLoggerBinder.class]))
```

**Comment by thomaszurkan-optimizely** [comment]
have you tried these entries in your proguard file?

# slf4j
-dontwarn org.slf4j.**

# Android Logger
-keep class com.noveogroup.android.log.** { *; }

**Comment by sayedhassan** [comment]
yes i have all the required entries in Proguard but it doesn't work. If you look at the error, it's caused by a class defined in the logger library that has exactly the same name as the one in the slf4j library

**Comment by wkarl** [comment]
@thomaszurkan-optimizely the ProGuard rules are already provided (thanks again for adding this to 1.4.0) so it shouldn't make a difference whether or not you add them again.

**Comment by thomaszurkan-optimizely** [comment]
@sayedhassan how are you building, gradle?  are you including the bintray files?  are you trying to include another logger library and that is where the problem is coming in?  I'm just trying to understand the issue.

**Comment by sayedhassan** [comment]
@thomasgodwell-optimizely i am building via gradle. and just included the gradle repo for optimizely. I haven't included any logger library but s4flj is used by other dependencies internally and i can see that nova logger has a package with the exact same name as the actual s4flj library.

**Comment by thomaszurkan-optimizely** [comment]
How are you including those dependencies?  via ```compile group``` and  ```provided group``` ?
  Have you tried ```compileOnly``` ?

**Comment by thomaszurkan-optimizely** [comment]
So, we can't remove the Simple Log 4 Java usage because we integrate with our core Java SDK and need a way to agree on logging.  If you have any suggestions, let me know.  However, if you look at the test_app gradle file, I have included examples of how to override the logger and parser.
https://github.com/optimizely/android-sdk/blob/master/test-app/build.gradle

**Comment by benoitdion** [comment]
removing android-logger is already an improvement

**Comment by thomaszurkan-optimizely** [comment]
Show an example how to exclude android-logger and add your own via test-app.

**Comment by djleeds** [comment]
It looks like the `android-logger` is still included in the `shared` module -- see the [build.gradle file](https://github.com/optimizely/android-sdk/blob/1.6.x/shared/build.gradle#L55) -- so it still ends up in the published aar file, which means that if an app has its own implementation of `org.slf4j.impl.StaticLoggerBinder` (or includes another dependency that does), you'll end up with this build error:

```
Program type already present: org.slf4j.impl.StaticLoggerBinder
```

Or if you're on Android build tools 3.0 or lower, it'll look like this:

```
Multiple dex files define Lorg/slf4j/impl/StaticLoggerBinder;
```

As pointed out above, you can work around this by excluding that dependency - here's what that looks like:
```
implementation('com.optimizely.ab:android-sdk:1.6.0') {
    exclude group: 'com.noveogroup.android', module:'android-logger'
}
```

Would it be possible to remove the `android-logger` implementation from the `shared` module as well? You might have already seen it, but the [libraries section](https://www.slf4j.org/manual.html#libraries) of the slf4j manual says that the basic rule is: 

> "Embedded components such as libraries or frameworks should not declare a dependency on any SLF4J binding but only depend on slf4j-api."

Anyway, if it's possible to remove the dependency on `android-logger` but keep the dependency on the slf4j-api, that would be ideal for any apps that are also using slf4j.  If that's not an option, then a nice alternative would be to update the [Getting Started documentation](https://developers.optimizely.com/x/solutions/sdks/getting-started/index.html?language=android&platform=mobile#install-sdk) with information about this.

Thanks!

**Comment by thomaszurkan-optimizely** [comment]
Thanks for reporting this!  We did update the developer documents as you suggested.  Right now, we do include default logging (noveogroup) and json parsers (gson).  You can, as you mentioned, override them using gradle exclude as shown in the test app  https://github.com/optimizely/android-sdk/tree/master/test-app which we also included in the dev docs.  I hope this helps.
