### ISSUE TITLE
unable to override logger

### ISSUE THREAD

**Issue by jia-tse-zocdoc** [optimizely/android-sdk#143]
per the instructions here

[https://developers.optimizely.com/x/solutions/sdks/reference/index.html?language=android&platform=mobile#logger](url)

does the folder have to be in `src/main/resources`? 

I have `src/main/res`, and I can't seem to override the logging. I've created the file `src/main/res/android-logger.properties` with the example logger properties

**Comment by thomaszurkan-optimizely** [comment]
Yes, src/main/resources.

**Comment by jia-tse-zocdoc** [comment]
@thomaszurkan-optimizely seems that if I reference the libraries in a local aar, the logging behaves differently. It may not be able to read the override. 

I did `assembleRelease` from the root directory and took the resulting *release-aars from `android-sdk`, `datafile-handler`, `event-handler`, `shared` and `user-profile`. Is this the right way to do it?

**Comment by thomaszurkan-optimizely** [comment]
How about using the bintray release?:  https://bintray.com/optimizely/optimizely/optimizely-sdk-android.  Then, you can just put this in your gradle file:
compile 'com.optimizely.ab:android-sdk:1.4.0'
The repository is jcenter.

**Comment by jia-tse-zocdoc** [comment]
I can't take that because I have to modify the source code to use the v2 datafile instead of 3

**Comment by thomaszurkan-optimizely** [comment]
well, if that is the case, why don't you just replace/modify the android.properties file in the android-sdk/resources directory?

**Comment by jia-tse-zocdoc** [comment]
Yes, I should just do that

**Comment by thomaszurkan-optimizely** [comment]
Ok, I'm going to close this issue again.
