### ISSUE TITLE
SDK isn't updating with new datafile

### ISSUE THREAD

**Issue by jia-tse-zocdoc** [optimizely/android-sdk#144]
I think the issue is 2-fold

1) I added a new variation onto my experiment, and verified the datafile is updated in the CDN by hitting the url on my browser. `DatafileClient` reports that "Data file has not been modified on the cdn"

2) In debug mode, I've overridden `urlConnection.setIfModifiedSince(lastModified)` to have a value of 1 day prior. A new datafile was downloaded, but when I accessed

`optimizelyClient?.projectConfig?.experimentKeyMapping.get(expKey).variations` 

The client itself isn't updated to use the new file. 

A restart of the application seems to have refreshed the file.

**Comment by thomaszurkan-optimizely** [comment]
I'm not sure what initialization you are using.  But, using the test-app I changed it to my project id and had it download the datafile.  Then, I updated the datafile, and it was caught and downloaded immediately.  So, I think you may have missed where the datafile actually got downloaded and then subsequent calls would have said 'Data file has not been modified on the cdn.'   Keep in mind that even if the datafile is downloaded, it is just moved to cache and you would have to use that cached version in a subsequent restart (the datafile is not updated for the current running optimizely instance).  That is to make sure that the users experience while running the app is the same even if the experiment changed.  On the next restart, the user would run through bucketing again or use user profile services.  Does that make sense?  The project file is definitely being picked up properly.

**Comment by jia-tse-zocdoc** [comment]
having a subsequent restart would work for us. Thank you!
