### ISSUE TITLE
Espresso Idling Resource Dependency

### ISSUE THREAD

**Issue by quarklemotion** [optimizely/android-sdk#150]
Copying customer issue reported here from Optiverse:
https://community.optimizely.com/t5/Mobile-Apps/Espresso-Idling-Resource-Dependency/m-p/20874

---
Is there any reason the Android SDK depends on com.android.support.test.espresso:espresso-idling-resource:2.2.2 in the release SDK?  Because of this, there's a dependency resolution conflict which is deeply unhelpful when we're trying to work on our test suite and use a different version of the Espresso libraries.  
 
I spent some time looking at the SDK source on GitHub, and it looks like it's only used in a class called CountingIdlingResourceManager.  Unless that data is read from this in some kind of very non-obvious way, it looks like data gets put into this thing, but is never read out.  So that's nice. 
 
Please remove this apparently superfluous dependency.  Having release code contain a testing library in this way seems like a mistake.  Use whatever you want in your test suites, just keep it out of the stuff that goes into the wild.

**Comment by thomaszurkan-optimizely** [comment]
Espresso dependency has been removed from the SDK build in 1.5.0-RC.  We will be closing this ticket soon.

**Comment by thomaszurkan-optimizely** [comment]
removed in 1.5.0
