### ISSUE TITLE
Release 1.5.0-RC Proguard Issues with < v26 Build Tools

### ISSUE THREAD

**Issue by geoffpowell-vividseats** [optimizely/android-sdk#159]
You should mention in your release notes about upgrading to v26.x.x for Android Build Tools for 1.5.0-RC. `android.app.job.JobWorkItem` is part of the v26.x.x build tools and you use this for the JobScheduler. 

If you point to anything below 26 you will see these proguard warnings:

`Warning:` com.optimizely.ab.android.shared.JobWorkService: can't find referenced class android.app.job.JobWorkItem
Warning: com.optimizely.ab.android.shared.JobWorkService: can't find referenced class android.app.job.JobWorkItem
Warning: com.optimizely.ab.android.shared.JobWorkService: can't find referenced method 'void completeWork(android.app.job.JobWorkItem)' in library class android.app.job.JobParameters
Warning: com.optimizely.ab.android.shared.JobWorkService: can't find referenced class android.app.job.JobWorkItem
Warning: com.optimizely.ab.android.shared.JobWorkService: can't find referenced class android.app.job.JobWorkItem
Warning: com.optimizely.ab.android.shared.JobWorkService: can't find referenced class android.app.job.JobWorkItem
Warning: com.optimizely.ab.android.shared.JobWorkService: can't find referenced class android.app.job.JobWorkItem
Warning: com.optimizely.ab.android.shared.JobWorkService: can't find referenced class android.app.job.JobWorkItem
Warning: com.optimizely.ab.android.shared.JobWorkService: can't find referenced class android.app.job.JobWorkItem
Warning: com.optimizely.ab.android.shared.JobWorkService$CommandProcessor: can't find referenced method 'android.app.job.JobWorkItem dequeueWork()' in library class android.app.job.JobParameters
Warning: com.optimizely.ab.android.shared.JobWorkService$CommandProcessor: can't find referenced class android.app.job.JobWorkItem
Warning: com.optimizely.ab.android.shared.JobWorkService$CommandProcessor: can't find referenced class android.app.job.JobWorkItem
Warning: com.optimizely.ab.android.shared.JobWorkService$CommandProcessor: can't find referenced class android.app.job.JobWorkItem
Warning: com.optimizely.ab.android.shared.JobWorkService$CommandProcessor: can't find referenced class android.app.job.JobWorkItem
Warning: com.optimizely.ab.android.shared.JobWorkService$CommandProcessor$1: can't find referenced class android.app.job.JobWorkItem
Warning: com.optimizely.ab.android.shared.JobWorkService$CommandProcessor$1: can't find referenced class android.app.job.JobWorkItem
Warning: com.optimizely.ab.android.shared.ServiceScheduler: can't find referenced class android.app.job.JobWorkItem
Warning: com.optimizely.ab.android.shared.ServiceScheduler: can't find referenced class android.app.job.JobWorkItem
Warning: com.optimizely.ab.android.shared.ServiceScheduler: can't find referenced method 'int enqueue(android.app.job.JobInfo,android.app.job.JobWorkItem)' in library class android.app.job.JobScheduler`

**Comment by thomaszurkan-optimizely** [comment]
Thanks for the feedback!  I'm adding that note right now and we are releasing 1.5 early next week.

**Comment by thomaszurkan-optimizely** [comment]
Added it to the change log and release notes.
