### ISSUE TITLE
1.5.0 Proguard issue with payload objects getting sent correctly to optimizely backend

### ISSUE THREAD

**Issue by geoffpowell-vividseats** [optimizely/android-sdk#162]
With the latest release 1.5.0 it says that the proguard file is included in the sdk. 
We noticed our activate and track calls not showing up in the optimizely dashboard. 
Then we saw that the payload was being obfuscated like so:
```
{
  "c": "UserID",
  ...
  "k": false,
  "m": "22",
  "a": "android-sdk",
  "b": "1.5.0"
}
```

So then looking through your src we added the following proguard rules to get it to work end to end.

Proguard Rules:
```
# Keep Payload classes that get sent to Optimizely's backend
-keep class com.optimizely.ab.event.internal.payload.** { *; }

# Keep these for logging purposes
-keep class com.optimizely.ab.bucketing.DecisionService { *; }
-keep class com.optimizely.ab.Optimizely { *; }
```

Just wanted to ask if this is because of our Proguard config or could it be a change to the libraries proguard config?

**Comment by thomaszurkan-optimizely** [comment]
We tried to narrow the scope of the proguard rules and made them too narrow.  I will update a patch today.  Thank you!

**Comment by thomaszurkan-optimizely** [comment]
1.5.1 was released.  We removed 1.5.0
