### ISSUE TITLE
SecurityException: Caller no longer running, last stopped

### ISSUE THREAD

**Issue by marcoRS** [optimizely/android-sdk#166]
We are seeing the following error using 1.5.1

```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:353)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
Caused by java.lang.SecurityException: Caller no longer running, last stopped +8s783ms because: timed out while starting
       at android.os.Parcel.readException(Parcel.java:1942)
       at android.os.Parcel.readException(Parcel.java:1888)
       at android.app.job.IJobCallback$Stub$Proxy.dequeueWork(IJobCallback.java:191)
       at android.app.job.JobParameters.dequeueWork(JobParameters.java:196)
       at com.optimizely.ab.android.shared.JobWorkService$CommandProcessor.doInBackground(JobWorkService.java:73)
       at com.optimizely.ab.android.shared.JobWorkService$CommandProcessor.doInBackground(JobWorkService.java:56)
```

**Comment by thomaszurkan-optimizely** [comment]
It appears from the error that it timed out after 8+ seconds which is pretty long for a job to be running. Could this be related to a network issue?   If it is a event, it should have been saved to SQLite and attempted to resend later.  Do, you know if this is something that clears up?

**Comment by marcoRS** [comment]
At the moment we are currently using the sdk only to log events. This seems to be a network issue however I'm unable to figure out the root cause. We have not changed our event logging much other then adding some params to an event.

**Comment by thomaszurkan-optimizely** [comment]
The good news is that it should retry and eventually succeed at some interval if you use EventDispatchInterval.

Pretty sure this would be happening at wifi change.  Also, this would be a Android O+ issue (only in Android O and later).  Do you have the following in your manifest?:

https://github.com/optimizely/android-sdk/blob/master/test-app/src/main/AndroidManifest.xml

Also, in the test_app as in your app, you need to register the intent filter in code now for Android O:

        // with the new Android O differences, you need to register the service for the intent filter you desire in code instead of
        // in the manifest.
        EventRescheduler eventRescheduler = new EventRescheduler();

        getApplicationContext().registerReceiver(eventRescheduler, new IntentFilter(WifiManager.SUPPLICANT_CONNECTION_CHANGE_ACTION));

**Comment by marcoRS** [comment]
Our manifest file is setup correctly like the test-app however we didn't know that we had to register an intent filter in code for Android 0. 

I'm wondering why in the test-app this is done in a Splash activity and not in the Application class? My first instinct would be to do this in the Application class so that it is only done once. Also why is this code not wrapped in a if-statement that checks for Android O version?

**Comment by thomaszurkan-optimizely** [comment]
1.  The reason it is in the Splash activity is just a bad refactor.  At first, we had the register inside the activate for asynchronous.  Then, we added a synchronous example and just left the register in the splash activity on start.  It can definitely be done in the application.
2.  There is no need to wrap the register since it is from Android 2 and works for all versions (the manifest entry is just a fallback or a notation).

**Comment by marcoRS** [comment]
Thanks that makes sense!

**Comment by thomaszurkan-optimizely** [comment]
This is now mentioned in the README, CHANGELOG, and developer docs.  So, going to close it.

**Comment by rykugur** [comment]
I used to work with Marco but he left the company, so I'm taking over this issue. This bug has re-surfaced as of/around March 23rd. Would you prefer I open a separate issue? 

99% of the crashes we're seeing in Crashlytics are users on Android O. The changes referenced above (creating an intent filter in code in addition to the manifest) were released to our users back in December and we saw the problem go away (or was significantly reduced) until now. We're currently seeing about 800-1000 crashes a day.

**Comment by thomaszurkan-optimizely** [comment]
I would say open a new issue.  Can you provide us with a crash log and/or stack track?  Is it a specific version of Android O?  How about specific device?  I don't know of any change on March 23.  Are you sure you are registering the intent filter on the application context?  As a fix, I will also wrap that dequeue call in a exception and return.  Thanks
