### ISSUE TITLE
403 while using the new SDK_KEY

### ISSUE THREAD

**Issue by jia-tse-zocdoc** [optimizely/android-sdk#218]
Hi,

I noticed in the logs that there is a 403 error while trying to access the URL with a `SDK_KEY`. This is how the URL looks like. `https://cdn.optimizely.com/datafiles/<SDK_KEY>.json`

Is there a missing step I'm supposed to do while using `SDK_KEY`?

Thanks,
Jia

**Comment by aliabbasrizvi** [comment]
Hi @jia-tse-zocdoc 

Can you confirm that you are providing the `SDK_KEY` as you see in your Optimizely account's project?

-- Ali

**Comment by aliabbasrizvi** [comment]
@jia-tse-zocdoc will it be possible for you to share project ID? Email ali at optimizely dot com. I can take a closer look.
