### ISSUE TITLE
UserProfileCache.DiskCache uses deprecated project ID

### ISSUE THREAD

**Issue by michaelpearce-at** [optimizely/android-sdk#221]
I noticed while integrating the SDK that the `UserProfileCache.DiskCache` is using the `projectId` in the `getFileName()` method. However, project IDs have been deprecated as of 2.1.0. 

We are currently initializing the OptimizelyManager with an SDK key, and *not* a project ID. This results in the disk cache being created with the filename `optly-user-profile-service-null.json` no matter what project or environment is being used. This could potentially lead to collisions.

**Comment by mikeng13** [comment]
Thanks for submitting this feedback! We'll look into it shortly.

**Comment by thomaszurkan-optimizely** [comment]
https://github.com/optimizely/android-sdk/pull/226

**Comment by thomaszurkan-optimizely** [comment]
fixed with release 2.1.1
