### ISSUE TITLE
unable to suppress SDK logs

### ISSUE THREAD

**Issue by jia-tse-zocdoc** [optimizely/android-sdk#230]
According to https://docs.developers.optimizely.com/full-stack/docs/configure-the-logger, I can create a `android-logger.properties` file under the `src/release/resources` directory. 

And supposedly this line will disable `most` SDK logs.   How can I disable `all` SDK logs? 

```
# Disable most SDK logs by commenting all other lines and uncommenting below
logger.com.optimizely.ab=ASSERT:Optly
```

**Comment by thomaszurkan-optimizely** [comment]
@jia-tse-zocdoc what log messages are you seeing that you would like removed?  as far as i can see you only see a couple of messages at startup and that is it.

**Comment by jia-tse-zocdoc** [comment]
I'm all good now. For some reason, the "bug" appeared out of the blue, and then it disappeared on its own. Probably the local state was invalid somehow.
