### ISSUE TITLE
Optimizely initialization without downloading Datafile

### ISSUE THREAD

**Issue by AndreBaltazar8** [optimizely/android-sdk#300]
Hello,

We are using this Android SDK on a Kotlin application to control experiments and features for thousands of devices which have bandwidth restrictions. We want to control when the datafile updated, so we are not using polling to prevent wasting bandwidth. The issue here is that this SDK will download the datafile every time the client is initialized.

The methods provided do not allow initializing the manager without downloading cache file. The following method,
https://github.com/optimizely/android-sdk/blob/7139c215ff8eb259871a4a6e81011da68692c957/android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java#L178
is prepared to receive a flag to decide if it should download or not, but there is no path where this is called with the value `false`. We think this method should have been public, instead of protected.

There are two alternatives to this, which are:
 - Creating a custom DatafileHandler, which will block certain request, but since using your methods to download the cache files, this would be tricky requiring changing some flags or something to know if we are initializing and blocking those, which feels like too much on an hack
 - Call that initialization method with reflection, which is not really ideal, but is the solution we are using right now

Is there any alternative? What is the recommended approach for this? Would it be possible to make that method public?

Thank you

**Comment by AndreBaltazar8** [comment]
Hey,

Thank you for the quick fix on that issue 👍 this will really help us get rid of the reflection, and take control over the initialization.

Do you have any idea on when this will be available for us to use?

Thank you again

**Comment by thomaszurkan-optimizely** [comment]
Released version 3.2.1 today.

**Comment by thomaszurkan-optimizely** [comment]
I'm going to close this issue since that method is now public in 3.2.1

**Comment by AndreBaltazar8** [comment]
Awesome, thank you
