### ISSUE TITLE
Stale value is returned after refresh

### ISSUE THREAD

**Issue by technoir42** [optimizely/android-sdk#310]
Steps to reproduce:

1. Initialize Optimizely SDK (3.3.0) like this:
```kotlin
val optimizelyClient = OptimizelyManager.builder()
    .withSDKKey("sdk key")
    .build(context)
    .initialize(context, R.raw.optimizely_data_file)
```
2. Enable/disable a feature flag in Optimizely console.
3. Wait for a few minutes just in case.
4. Launch the app and wait for a new data file to be downloaded from CDN.
5. Query the feature flag - `isFeatureEnabled` returns the previous value:
```kotlin
val enabled = optimizelyClient.isFeatureEnabled("test_flag", "123")
```
6. Kill the application process and restart.
7. Query the feature flag again - new value is returned.

**Comment by jaeopt** [comment]
@technoir42 Background datafile polling is off by default. To enable it, the polling interval in secs should be set like this:

val optimizelyClient = OptimizelyManager.builder()
    .withSDKKey("sdk key")
    .withDatafileDownloadInterval(600)
    .build(context)
    .initialize(context, R.raw.optimizely_data_file)

We'll improve the document to make it more clear. 
Let us know if this fixes your issue.

**Comment by technoir42** [comment]
Thanks for response.
We are not going to use background datafile polling and the bug is not related to it.
After creating this ticket I found out that the bug exists on Android 10 and doesn't exist on Android 9. Hope that helps.

**Comment by jaeopt** [comment]
I see. Thanks for your input.
We'll check Android 9 vs 10 here and get you updated.

**Comment by ar-g** [comment]
It's not only related to Android 9 and 10 but to all versions. The data file is updated but we getting cached values until the app restarts.

**Comment by thomaszurkan-optimizely** [comment]
@ar-g we updated the api so that now you can specify if you would like to be updated if a new datafile is downloaded after synch initialization without polling.
