### ISSUE TITLE
Event Flushing? 

### ISSUE THREAD

**Issue by jam0cam** [optimizely/android-sdk#314]
@thomaszurkan-optimizely Is there a way to flush events? i.e...., if my dispatch interval was configured at 30 seconds, but there are some important metrics I want to dispatch immediately. I can't find information around flushing.

Thanks.

**Comment by jam0cam** [comment]
looks like events are not batched at all. dispatch interval is only useful in the case of retries

**Comment by thomaszurkan-optimizely** [comment]
Hi, sorry for getting back to you a little late. In the latest SDK batching is happening within the java sdk and then sent out via the android event dispatcher.  You may be able to call dispatch off of the event dispatcher. But, it might be hard to tell if it was successful

**Comment by thomaszurkan-optimizely** [comment]
Hi, sorry for getting back to you a little late. In the latest SDK batching is happening within the java sdk and then sent out via the android event dispatcher.  You can try calling dispatch off of the dispatcher
