### ISSUE TITLE
Upgrade to Android X 

### ISSUE THREAD

**Issue by ber4444** [optimizely/android-sdk#345]
Getting

```
Cannot drop Jetifier due to following external dependencies:

com.optimizely.ab:android-sdk:3.6.0
```

with the plugin described here: https://adambennett.dev/2020/08/disabling-jetifier/

**Comment by DanielMartinus** [comment]
Optimizely is also the only SDK in our app not migrated to androidX yet. Would love to see the SDK migrated so that we can drop Jetifier.

**Comment by thederputy** [comment]
This is still an issue in the latest 3.7.0 SDK:

```
Cannot drop Jetifier due to following external dependencies:

* com.optimizely.ab:android-sdk:3.7.0
```

**Comment by kevinzetterstrom** [comment]
Would love to understand if there is a timeline here, suffering the same issue!

**Comment by jeremybl-sportsbet** [comment]
Only Lib preventing us to drop Jetifier too

**Comment by riggaroo** [comment]
Any update on this?

**Comment by kevinzetterstrom** [comment]
Any update on when a release will include this? I see the change was merged about 2 weeks ago - I understand there may be additional changes you wish to release simultaneously, but it would be great to push a release so consumers can migrate off Jetifier

**Comment by thomaszurkan-optimizely** [comment]
@kevinzetterstrom should be going out in the next couple of weeks.

**Comment by thomaszurkan-optimizely** [comment]
@kevinzetterstrom 3.9.0 has been released which includes update to androidX.  I'm closing this issue.
