### ISSUE TITLE
SUPPLICANT_CONNECTION_CHANGE_ACTION is deprecated in API 28

### ISSUE THREAD

**Issue by beraldofilippo** [optimizely/android-sdk#347]
Hello,

following the SDK docs I have noticed that when registering a broadcast receive to retrieve connection change events we're required to use `IntentFilter(WifiManager.SUPPLICANT_CONNECTION_CHANGE_ACTION)`. 

It looks like now that `SUPPLICANT_CONNECTION_CHANGE_ACTION` has been deprecated since API 28, and by the looks of it there's no quick way around this. What would you suggest here?

Thanks

**Comment by thomaszurkan-optimizely** [comment]
@beraldofilippo thanks for the heads up.  We will look into it.  In the meantime.  Just don't register the event rescheduler for the supplicant connection change.

**Comment by thomaszurkan-optimizely** [comment]
https://github.com/optimizely/android-sdk/releases/tag/3.10.0
It's been removed
