### ISSUE TITLE
AsyncTask is deprecated in API 30 (Android 11)

### ISSUE THREAD

**Issue by byunlee** [optimizely/android-sdk#351]
https://developer.android.com/reference/android/os/AsyncTask

Android documentation says:
```
This class was deprecated in API level 30.
Use the standard java.util.concurrent or Kotlin concurrency utilities instead.
```

I see AsyncTask being used in a few places. It should be replaced with something else.

**Comment by thomaszurkan-optimizely** [comment]
https://github.com/optimizely/android-sdk/releases/tag/3.10.0
