### ISSUE TITLE
Move to MavenCentral?

### ISSUE THREAD

**Issue by jonamireh** [optimizely/android-sdk#361]
[Starting from May 1, 2021 jCenter & Bintray will stop working](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter). I was looking for the `com.optimizely.ab` artifacts (specifically, `core-api`, `android-sdk-datafile-handler`, `android-sdk-event-handler`, `android-sdk-user-profile`, `android-sdk-shared`, `android-sdk`)  in MavenCentral and didn't find it. **Are there any plans to move away from jCenter?**

**Comment by jaeopt** [comment]
@jonamireh Thanks for sharing it. We're looking into options for moving from jcenter. We'll get you updated.
