### ISSUE TITLE
Optimizely does not initialize without proguard rule for Gson

### ISSUE THREAD

**Issue by sshah112** [optimizely/android-sdk#378]
Optimizely is not being initialized because there is an error while parsing the datafile. Digging in deeper, it is discovered that proguard is being applied to field names in Gson library, causing `java.lang.RuntimeException: Missing type parameter`. Since Gson is used internally by Optimizely, it is necessary to add proguard rule to exclude Gson :

- maybe `-keep class com.google.gson.**` inside https://github.com/optimizely/android-sdk/blob/master/proguard-rules.txt

**Comment by jaeopt** [comment]
@sshah112 Thanks for reporting. We'll look into the issue.

**Comment by sshah112** [comment]
> @sshah112 Thanks for reporting. We'll look into the issue.

thank you!

**Comment by inktomi** [comment]
I see the same, an error about being unable to parse the datafile. 

```
E/DefaultDatafileHandler: com.optimizely.ab.config.parser.ConfigParseException: Unable to parse datafile: {...}
E/DefaultDatafileHandler:     at com.optimizely.ab.config.parser.GsonConfigParser.parseProjectConfig(SourceFile:60)
E/DefaultDatafileHandler:     at com.optimizely.ab.config.DatafileProjectConfig$Builder.build(SourceFile:497)
E/DefaultDatafileHandler:     at com.optimizely.ab.android.datafile_handler.DefaultDatafileHandler.setDatafile(SourceFile:307)
E/DefaultDatafileHandler:     at com.optimizely.ab.android.sdk.OptimizelyManager.buildOptimizely(SourceFile:574)
E/DefaultDatafileHandler:     at com.optimizely.ab.android.sdk.OptimizelyManager.injectOptimizely(SourceFile:524)
E/DefaultDatafileHandler:     at com.optimizely.ab.android.sdk.OptimizelyManager$2.onDatafileLoaded(SourceFile:405)
E/DefaultDatafileHandler:     at com.optimizely.ab.android.datafile_handler.DefaultDatafileHandler$1.onDatafileLoaded(SourceFile:95)
E/DefaultDatafileHandler:     at com.optimizely.ab.android.datafile_handler.DatafileLoader.notifyListener(SourceFile:133)
E/DefaultDatafileHandler:     at com.optimizely.ab.android.datafile_handler.DatafileLoader.access$500(SourceFile:38)
E/DefaultDatafileHandler:     at com.optimizely.ab.android.datafile_handler.DatafileLoader$1.run(SourceFile:120)
E/DefaultDatafileHandler:     at com.optimizely.ab.config.parser.DatafileGsonDeserializer$1.<init>(SourceFile:50)
E/DefaultDatafileHandler:     at com.optimizely.ab.config.parser.DatafileGsonDeserializer.deserialize(SourceFile:50)
E/DefaultDatafileHandler:     at com.optimizely.ab.config.parser.DatafileGsonDeserializer.deserialize(SourceFile:36)
E/DefaultDatafileHandler:     at com.optimizely.ab.config.parser.GsonConfigParser.parseProjectConfig(SourceFile:58)
```

**Comment by sshah112** [comment]
> I see the same, an error about being unable to parse the datafile.
> 
> ```
> E/DefaultDatafileHandler: com.optimizely.ab.config.parser.ConfigParseException: Unable to parse datafile: {...}
> E/DefaultDatafileHandler:     at com.optimizely.ab.config.parser.GsonConfigParser.parseProjectConfig(SourceFile:60)
> E/DefaultDatafileHandler:     at com.optimizely.ab.config.DatafileProjectConfig$Builder.build(SourceFile:497)
> E/DefaultDatafileHandler:     at com.optimizely.ab.android.datafile_handler.DefaultDatafileHandler.setDatafile(SourceFile:307)
> E/DefaultDatafileHandler:     at com.optimizely.ab.android.sdk.OptimizelyManager.buildOptimizely(SourceFile:574)
> E/DefaultDatafileHandler:     at com.optimizely.ab.android.sdk.OptimizelyManager.injectOptimizely(SourceFile:524)
> E/DefaultDatafileHandler:     at com.optimizely.ab.android.sdk.OptimizelyManager$2.onDatafileLoaded(SourceFile:405)
> E/DefaultDatafileHandler:     at com.optimizely.ab.android.datafile_handler.DefaultDatafileHandler$1.onDatafileLoaded(SourceFile:95)
> E/DefaultDatafileHandler:     at com.optimizely.ab.android.datafile_handler.DatafileLoader.notifyListener(SourceFile:133)
> E/DefaultDatafileHandler:     at com.optimizely.ab.android.datafile_handler.DatafileLoader.access$500(SourceFile:38)
> E/DefaultDatafileHandler:     at com.optimizely.ab.android.datafile_handler.DatafileLoader$1.run(SourceFile:120)
> E/DefaultDatafileHandler:     at com.optimizely.ab.config.parser.DatafileGsonDeserializer$1.<init>(SourceFile:50)
> E/DefaultDatafileHandler:     at com.optimizely.ab.config.parser.DatafileGsonDeserializer.deserialize(SourceFile:50)
> E/DefaultDatafileHandler:     at com.optimizely.ab.config.parser.DatafileGsonDeserializer.deserialize(SourceFile:36)
> E/DefaultDatafileHandler:     at com.optimizely.ab.config.parser.GsonConfigParser.parseProjectConfig(SourceFile:58)
> ```

There is a second part to this stacktrace which I also missed until just now
<img width="504" alt="Screen Shot 2021-08-19 at 9 47 28 AM" src="https://user-images.githubusercontent.com/62890661/130079938-a8f73207-c335-47d5-a0b1-ab1e392bd4cc.png">

Along with the rules for optimizely that are provided by the team (https://github.com/optimizely/android-sdk/blob/master/proguard-rules.txt), since the library uses Gson, rule needed to be added to exclude Gson as well.
For now `-keep class com.google.gson.**`, but hopefully can narrow this down to something more specific.

**Comment by jaeopt** [comment]
@sshah112 @inktomi We can replace the GSON proguard rule with one recommended in gson repo: https://github.com/google/gson/blob/master/examples/android-proguard-example/proguard.cfg

Can you try with this and let us know if it works for you? Tx!

```
##---------------Begin: proguard configuration for Gson  ----------
# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature

# For using GSON @Expose annotation
-keepattributes *Annotation*

# Gson specific classes
-dontwarn sun.misc.**

# Prevent proguard from stripping interface information from TypeAdapter, TypeAdapterFactory,
# JsonSerializer, JsonDeserializer instances (so they can be used in @JsonAdapter)
-keep class * extends com.google.gson.TypeAdapter
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

# Prevent R8 from leaving Data object members always null
-keepclassmembers,allowobfuscation class * {
  @com.google.gson.annotations.SerializedName <fields>;
}

# Retain generic signatures of TypeToken and its subclasses with R8 version 3.0 and higher.
-keep,allowobfuscation,allowshrinking class com.google.gson.reflect.TypeToken
-keep,allowobfuscation,allowshrinking class * extends com.google.gson.reflect.TypeToken
##---------------End: proguard configuration for Gson  ----------
```

**Comment by sshah112** [comment]
> @sshah112 @inktomi We can replace the GSON proguard rule with one recommended in gson repo: https://github.com/google/gson/blob/master/examples/android-proguard-example/proguard.cfg
> 
> Can you try with this and let us know if it works for you? Tx!
> 
> ```
> ##---------------Begin: proguard configuration for Gson  ----------
> # Gson uses generic type information stored in a class file when working with fields. Proguard
> # removes such information by default, so configure it to keep all of it.
> -keepattributes Signature
> 
> # For using GSON @Expose annotation
> -keepattributes *Annotation*
> 
> # Gson specific classes
> -dontwarn sun.misc.**
> 
> # Prevent proguard from stripping interface information from TypeAdapter, TypeAdapterFactory,
> # JsonSerializer, JsonDeserializer instances (so they can be used in @JsonAdapter)
> -keep class * extends com.google.gson.TypeAdapter
> -keep class * implements com.google.gson.TypeAdapterFactory
> -keep class * implements com.google.gson.JsonSerializer
> -keep class * implements com.google.gson.JsonDeserializer
> 
> # Prevent R8 from leaving Data object members always null
> -keepclassmembers,allowobfuscation class * {
>   @com.google.gson.annotations.SerializedName <fields>;
> }
> 
> # Retain generic signatures of TypeToken and its subclasses with R8 version 3.0 and higher.
> -keep,allowobfuscation,allowshrinking class com.google.gson.reflect.TypeToken
> -keep,allowobfuscation,allowshrinking class * extends com.google.gson.reflect.TypeToken
> ##---------------End: proguard configuration for Gson  ----------
> ```

This works for me! 👍

**Comment by sshah112** [comment]
Issue Addressed
