### ISSUE TITLE
Update SDK's dependencies

### ISSUE THREAD

**Issue by asos-edgeorge** [optimizely/android-sdk#396]
Hi Optimizely team,

We have noticed that some of your SDK's dependencies are out-of-date and can be updated

*   androidx.work:work-\* -> [2.7.1](https://developer.android.com/jetpack/androidx/releases/work#2.7.1)
*   com.google.code.gson:gson -> 2.8.9
*   androidx.annotation:annotation -> 1.2.0

I am sure there might be others, but would it be possible to update these in the next minor release of the SDK?

**Comment by jaeopt** [comment]
@asos-edgeorge Thanks for sharing. We'll update them in the next release.

**Comment by jaeopt** [comment]
@asos-edgeorge We released 3.13.2, which upgrades those dependencies.
