### ISSUE TITLE
List all Flags available

### ISSUE THREAD

**Issue by grmaciel** [optimizely/android-sdk#425]
Hello, i have seen is only possible to get the list of flags that are enabled. I would like to be able to know if a given flag is within the flags that have been set. Currently if the flag doesn't exist it just returns false.

Is there a way within the SDK for me to check if a flag exists remotely? I have seen from the REST api that there's an endpoint that provides all of the flags but couldn't find on the SDK.

Thanks,

**Comment by grmaciel** [comment]
`projectConfig` within the client has what i need, closing.

**Comment by jaeopt** [comment]
@grmaciel ProjectConfig is not for public access. We recommend to use OptimizelyConfig to access public config info. Details are in this doc page: https://docs.developers.optimizely.com/full-stack/docs/optimizelyconfig-android
