### ISSUE TITLE
AD Blocker is blocking the data sync

### ISSUE THREAD

**Issue by ercanpinar** [optimizely/android-sdk#427]
Sync data from Optimizely Issue on Android.
if I have an AD blocker app like (https://play.google.com/store/apps/details?id=com.rucksack.adblock.anti_tracking&hl=en_AU&gl=US) installed and turned on on my device.
Optimizely cannot get fresh data from Optimizely API.
I have tested with the latest build (https://github.com/optimizely/android-sdk/releases) still no luck. When I delete the AD blocker app, it works.

**Comment by jaeopt** [comment]
@ercanpinar We traced back the source of the issue - the adblocker app includes optimizely.com domain in their blacklist unexpectedly. We'll follow up to clean the list.
