### ISSUE TITLE
[BUG] Setting initialize()'s updateConfigOnNewDatafile=false is ignored by DefaultDatafileHandler

### ISSUE THREAD

**Issue by haroldteramotosonos** [optimizely/android-sdk#472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SDK Version

3.13.4

### Current Behavior

Initializing OptimizelyManager.initialize with `updateConfigOnNewDatafile` set to `false` is ignored by `DefaultDatafileHandler`.  DefaultDatafileHandler will still call `enableUpdateConfigOnNewDatafile()` regardless of the value of `updateConfigOnNewDatafile` and updates the configuration when the new datafile is downloaded.

### Expected Behavior

When `updateConfigOnNewDatafile` set to `false`, configuration is not updated as stated in the documentation.

### Steps To Reproduce

1. Initialize OptimizelyManager with 1 minute interval.
2. Call initialize() with `updateConfigOnNewDatafile` set to `false`
3. Change the flag to a different value from default.
4. Wait for at least 15 minutes for Optimizely to download the updated datafile. 

Expected:
- The flag should remain the same default value.

Actual:
- The flag gets updated to the latest value.

### Severity

Minor issue

### Workaround/Solution

Workaround that we implemented:
Subclass from `DefaultDatafileHandler` and overrode enableUpdateConfigOnNewDatafile() and make it a no-op.

**Comment by muzahidul-opti** [comment]
Hi @haroldteramotosonos thanks for raising the ticket. Which initialization approach did you follow? I mean synchronous or asynchronous.

**Comment by haroldteramotosonos** [comment]
We use synchronous initialization.  Apologies for missing that information.

**Comment by haroldteramotosonos** [comment]
I just checked the Swift SDK documentation and I see this in the doc.

>If you have datafile polling enabled, the Swift SDK automatically updates when a new datafile is detected to ensure that you are always working with the latest datafile. 

[Swift Usage Notes](https://docs.developers.optimizely.com/full-stack-experimentation/docs/initialize-sdk-swift#usage-notes)

However, on the Android documentation, this behavior is not documented.
[Android Usage Notes](https://docs.developers.optimizely.com/feature-experimentation/docs/initialize-sdk-android#section-configure-datafile-polling)

Could this be a documentation error, rather than the software defect?

**Comment by muzahidul-opti** [comment]
Hi @haroldteramotosonos, I really appreciate your effort. You are correct. If the 'datafileDownloadInterval' value is greater than 0, then `datafileDownloadEnabled` becomes true, and the SDK automatically downloads the latest data file.

We will update our doc very soon.

Thank you.

**Comment by haroldteramotosonos** [comment]
Thank you @muzahidul-opti for the clarification!  I will close this issue.
